
version: '3.1'

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.authc.token.enabled=false

    volumes:
      - /home/joaco/NAS/data/elasticsearch/data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200
    
    networks:
      - elastic 

  kib8:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
    ports:
      - 5601:5601
    networks:
      - elastic 
    depends_on:
      - es8

    volumes:
      - /home/joaco/NAS/data/kibana/data:/usr/share/kibana/data

networks:
  elastic:
    driver: bridge
