#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -u curl git software-properties-common ansible

##pull ansibel

sudo ansible-pull -U https://github.com/joaquinramirez/ansible.git
